% czas
dt = 0.01;
t=0:(end_time/dt); t=t*dt;

% sygnały
xw_ref_wybor = 4;
switch xw_ref_wybor
case 0
% troche bardziej zmienna
    xw_ref = ( ...
    utils.ustep(t, 0)*track_len/2 + ...
    utils.ustep(t, 1)*(0.35 - track_len/2) - ...
    utils.ustep(t, 4)*(0.25) .* 1 + ...
    utils.ustep(t, 8)*(track_len/2 - 0.1) );
case 1
% skok
    xw_ref = ( ...
    utils.ustep(t, 0)*track_len/2 + ...
    utils.ustep(t, 1)*(0.15) );
case 2
% sin
    T = 2;
    xw_ref = 0.1*utils.ustep(t, 1).*sin(2*pi/T * t) + utils.ustep(t, 0)*track_len/2;
case 3
% skok w t=0
    xw_ref = ( ...
    utils.ustep(t, 0)*track_len/2 );
case 4
% skok 2 polowa suwnicy
    xw_ref = ( ...
    utils.ustep(t, 0)*0.2 + ...
    utils.ustep(t, 10)*0.2 - ... 
    utils.ustep(t, 40)*0.2 - ... 
    utils.ustep(t, 70)*0.1 );
end
% xw_ref = ( utils.ustep(t, 0)*(0.103946) + ...
%            utils.ustep(t, 1.345)*(0.2) + ...
%            utils.ustep(t, 4.345)*(-0.2) + ... 
%            utils.ustep(t, 7.345)*(0.2) + ... 
%            utils.ustep(t, 10.345)*(-0.2) + ... 
%            utils.ustep(t, 13.345)*(0.2) + ...
%            utils.ustep(t, 16.345)*(-0.1) );
d = ( utils.ustep(t, 32) - ...
        utils.ustep(t, 35) ) * 0.06;
% d = - ( utils.ustep(t, 32) - ...
%         utils.ustep(t, 35) - ...
%         utils.ustep(t, 100) ) * 0.06;
% d = ( utils.ustep(t, 32) - ...
%       utils.ustep(t, 35) ) * 0.0;

% xw_ref = xw_ref*0;

ind.time = t;
ind.signals(1).values = xw_ref';
ind.signals(1).dimensions = 1;
ind.signals(2).values = d';
ind.signals(2).dimensions = 1;

